feat: key generation
chaosaffe/midsummer pull request #1
Opened 2018-06-29 10:30 UTC by chaosaffe

2018-06-29 17:15 UTC, moolen approved these changes
I'm missing the documentation. There are ~20 Exported types in the `pkg` dir which be documented.

IMO: It's fine to add the docs later once this thing is polished and production ready, since there are still things unimplemented (smartcard, yubikey).

2018-06-29 17:15 UTC, moolen commented on example.yaml
> +  preferredsymmetric:
What are those numbers? Not even `crypto/openpgp/packet` has docs about that. Same for the fields below

2018-06-29 17:15 UTC, moolen commented on main.go
> +	InputYes = "y\n"
Does this have to be exported? I'd suggest to un-export it.

2018-06-29 17:15 UTC, moolen commented on pkg/key/key.go
> +			panic("unknown key usage type")
i'd suggest to rather not panic inside a pkg. return an error and let that bubble up

2018-06-29 17:15 UTC, moolen commented on pkg/key/keyusage.go
> +		return errors.New("unknown usage type: " + s)
i suggest using `fmt.Errorf`

2018-06-29 20:29 UTC, mdomke requested changes

2018-06-29 20:29 UTC, mdomke commented on example.yaml
> +  usages:
GPG itself calls it "capabilites"

2018-06-29 20:29 UTC, mdomke commented on example.yaml
> +  expirydate: 1M
This should be called `expires_in` in my opinion, because it's not even a date. If it was I would still opt for `expires_at` as name.

2018-06-29 20:29 UTC, mdomke commented on example.yaml
> +  preferredsymmetric:
Additionally I think that all this keys would read better as `preferred_*`, so in this case `perferred_symmetric`.

2018-06-29 20:29 UTC, mdomke commented on pkg/fingerprint/fingerprint.go
> +	gs := "\t"
I know that there is a tendency in the Go community to name things like the mathematicians in the 70ies and I'm not saying that I'm all in favour for bulky Java-like names, but something a little more descriptive would be cool e.g. `ss = split` and `gs = grouped` or whatever…

2018-06-29 20:30 UTC, chaosaffe commented on example.yaml
> +  preferredsymmetric:
You can find them defined in https://tools.ietf.org/html/rfc4880#section-9
I plan to add textual representations and add custom marshalers for them them as a string _or_ int, but right now I wanted to focus on getting it working, then improving the UX

2018-06-29 20:32 UTC, chaosaffe commented on example.yaml
> +  expirydate: 1M
This can optionally be an RFC 3339 date, or a time period. I agree `expirydate` isn't a great field name, but as it can be either/or can you suggest a good name?

2018-06-29 22:48 UTC, chaosaffe commented on example.yaml
> +  usages:
I am trying to follow the GPG `batch` syntax, which refers to it as `Key-Usage`
Reference: https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

2018-06-30 22:11 UTC, mdomke commented on example.yaml
> +  expirydate: 1M
If you are fond of the idea to make this a field that can be either a date or a duration (which I'm not) I would maybe just name it `expires`.

2018-06-30 22:50 UTC, mdomke requested changes

2018-06-30 22:50 UTC, mdomke commented on pkg/fingerprint/fingerprint.go
> +	groupedStrings := "\t"
I know that I made you change these variable names from what they were originally (`ss` and `gs`), but I still would opt for my initial proposal (`split` and `grouped`). In my opinion the `Strings`-suffix doesn't add any value, because it's clear from the context that were dealing with strings here.
On the other hand you could also just inline the `strings.Split`-call and call the result accumulator `result`.

2018-06-30 22:50 UTC, mdomke commented on pkg/fingerprint/fingerprint.go
> +	for _, s := range splitStrings {
I would just use the index returned by `range` and do a modulo calculation. Here is my version
```go
func groupWords(s, sep string, size int) string {
	result := "\t"
	for i, word := range strings.Split(s, sep) {
		result += word
		if i > 0 && i%size == 0 {
			result += "\n\t"
		} else {
			result += " "
		}
	}
	return result
}
```

2018-07-01 06:57 UTC, christianhuening commented on example.yaml
> +  expirydate: 1M
Why does it have to support both date and period of time? Isn't the latter enough? "expires after this amount of time"

2018-07-01 14:05 UTC, chaosaffe commented on pkg/fingerprint/fingerprint.go
> +	for _, s := range splitStrings {
That is what I was doing originally (also, golang doesn't use `%` for modulus operator, you need to use `math.Mod()`), but it doesn't help much with readability (especially since `math.Mod()` takes and returns `float64`, so the conversions are cumbersome, and it means a performance hit...

2018-07-01 14:30 UTC, chaosaffe commented on example.yaml
> +  expirydate: 1M
@christianhuening, as mentioned above I am trying to follow the GPG batch syntax, which allows for a date _or_ duration, specifically `Expire-Date: iso-date|(number[d|w|m|y])`
Reference: https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

2018-07-01 21:59 UTC, mdomke commented on pkg/fingerprint/fingerprint.go
> +	for _, s := range splitStrings {
Wat? https://play.golang.org/p/9AcPnkikYWF

2018-07-02 05:23 UTC, christianhuening commented on pkg/fingerprint/fingerprint.go
> +	for _, s := range splitStrings {
math.Mod() is for floats, while `%` works solely on integers. So in this case IMHO `%` is perfectly fine

2018-07-02 12:14 UTC, moritzpein commented on example.yaml
> +  expirydate: 1M
`expires_after` would work with both: period length and a point in time (expiration date).

2018-07-02 23:22 UTC, chaosaffe commented on pkg/fingerprint/fingerprint.go
> +	for _, s := range splitStrings {
Well, learned something new today :)

2018-07-03 09:34 UTC, chaosaffe commented on example.yaml
> +  usages:
Can someone else chime in on this? I don't have an issue changing it if it makes it more understandable, and I am too biased to make an effective call.

//cc @moritzpein @moolen @christianhuening

2018-07-12 19:37 UTC, mdomke approved these changes

2018-07-17 08:07 UTC, merged